# Copyright © 2024-2026 Adam Train <adam@usdocument.org>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <https://www.gnu.org/licenses/>.

[package]
name = "ledr"
version = "2.1.6"
authors = ["Adam Train"]
edition = "2021"
description = "Plain text accounting tool"
readme = "README.md"
repository = "https://github.com/adamtrain/ledr"
license = "GPL-3"

[lints.rust]
unsafe_code = "forbid"

[dependencies]
anyhow = "1.0.100"
chrono = "0.4.42"
clap = { version = "4.5.53", features = ["derive"] }
dirs = "6.0.0"
rand = "0.9.0"
regex = "1.12.2"
reqwest = { version = "0.12.26", features = ["blocking", "json"] }
serde = { version = "1.0.228", features = ["derive"] }
toml = "0.9.10"
serde_json = "1.0.146"
